.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CARGO\-INSTALL\-UPDATE" "1" "January 2020" "cargo-update developers" ""
.
.SH "NAME"
\fBcargo\-install\-update\fR \- Cargo subcommand for checking and applying updates to installed executables
.
.SH "SYNOPSIS"
\fBcargo install\-update\fR [OPTIONS] [PACKAGE\.\.\.]
.
.SH "DESCRIPTION"
Cargo subcommand for checking and applying updates to installed executables\.
.
.P
This was mostly built out of a frustration with periodically checking for updates for my cargo\-installed executables, which was long and boring\.
.
.P
Updates packages from the main repository and git repositories\.
.
.P
See cargo\-install\-update\-config(1) for further configuring updates\.
.
.P
The \fBCARGO_INSTALL_OPTS\fR environment variable can be set, containing options to forward to the end of \fBcargo install\fR invocations\' argument lists\. Note, that cargo\-install\-update\-config(1) is preferred in the general case\.
.
.P
Exit values and possible errors:
.
.IP "" 4
.
.nf

\-1 \- cargo subprocess was terminated by a signal (Linux\-only)
1  \- option parsing error
2  \- registry repository error
X  \- bubbled\-up cargo install exit value
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
\-a \-\-all
.
.IP "" 4
.
.nf

Update all currently installed executables\.

Required if list of packages not given\.
.
.fi
.
.IP "" 0
.
.P
[PACKAGE\.\.\.]
.
.IP "" 4
.
.nf

List of packages to update\.

If specified in addition to \-\-all,
will add the specified packages to the update list
(useful, e\.g\., in conjunction with \-\-allow\-no\-update)\.

Required if \-\-all not given\.
.
.fi
.
.IP "" 0
.
.P
\-l \-\-list
.
.IP "" 4
.
.nf

Don\'t update any packages, just list them\.

If PACKAGE is empty, act as if \-\-all was specified\.
.
.fi
.
.IP "" 0
.
.P
\-f \-\-force
.
.IP "" 4
.
.nf

Update all packages, regardless of whether they need to be version\-wise\.
.
.fi
.
.IP "" 0
.
.P
\-i \-\-allow\-no\-update
.
.IP "" 4
.
.nf

Allow to fresh install packages passed as PACKAGE argument\.

This is useful, for example, in pairing with cargo\-install\-update\-config(1)\.

Off by default\.
.
.fi
.
.IP "" 0
.
.P
\-g \-\-git
.
.IP "" 4
.
.nf

Also update git\-originating packages\.

Off by default, because it\'s expensive\.
.
.fi
.
.IP "" 0
.
.P
\-q \-\-quiet
.
.IP "" 4
.
.nf

Don\'t print status messages to stdout
and pass down \-\-quiet to cargo subprocesses\.
.
.fi
.
.IP "" 0
.
.P
\-s \-\-filter \fIPACKAGE_FILTER\fR\.\.\.
.
.IP "" 4
.
.nf

Only consider packages matching all filters\.

PACKAGE_FILTER is in the form "key=value", where key is any of:
  \- "toolchain": the package must be configured to be compiled with
                 the specified toolchain via cargo\-install\-update\-config(1)\.
.
.fi
.
.IP "" 0
.
.P
\-c \-\-cargo\-dir \fICARGO_DIR\fR
.
.IP "" 4
.
.nf

Set the directory containing cargo metadata\.

Required\. Default: "$CARGO_HOME", then "$HOME/\.cargo", otherwise manual\.
.
.fi
.
.IP "" 0
.
.P
\-t \-\-temp\-dir \fITEMP_DIR\fR
.
.IP "" 4
.
.nf

Set the directory in which to clone git repositories\.

Adjoined with "cargo\-update" as last segment\.

Required\. Default: system temp, otherwise manual\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBcargo install\-update \-a\fR
.
.IP "" 4
.
.nf

Update all installed packages\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package         Installed  Latest   Needs update
  checksums       v0\.5\.0     v0\.5\.2   Yes
  treesize        v0\.2\.0     v0\.2\.1   Yes
  cargo\-count     v0\.2\.2     v0\.2\.2   No
  cargo\-graph     v0\.3\.0     v0\.3\.0   No
  cargo\-outdated  v0\.2\.0     v0\.2\.0   No
  identicon       v0\.1\.1     v0\.1\.1   No
  racer           v1\.2\.10    v1\.2\.10  No
  rustfmt         v0\.6\.2     v0\.6\.2   No

  Updating checksums
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading checksums v0\.5\.2
     [\.\.\.]
     Compiling checksums v0\.5\.2
      Finished release [optimized] target(s) in 95\.2 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\echecksums\.exe

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updated 2 packages\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update\fR \fIracer treesize cargo\-cln\fR
.
.IP "" 4
.
.nf

Only consider racer, treesize and cargo\-cln for updates\.
Since cargo\-cln is not installed, it\'ll be ignored\.

 Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package   Installed  Latest   Needs update
  racer     v1\.2\.10    v1\.2\.10  No
  treesize  v0\.2\.0     v0\.2\.1   Yes

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updated 1 package\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-al\fR
.
.IP "" 4
.
.nf

List all installed packages, don\'t update any\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package         Installed  Latest   Needs update
  checksums       v0\.5\.0     v0\.5\.2   Yes
  treesize        v0\.2\.0     v0\.2\.1   Yes
  cargo\-count     v0\.2\.2     v0\.2\.2   No
  cargo\-graph     v0\.3\.0     v0\.3\.0   No
  cargo\-outdated  v0\.2\.0     v0\.2\.0   No
  identicon       v0\.1\.1     v0\.1\.1   No
  racer           v1\.2\.10    v1\.2\.10  No
  rustfmt         v0\.6\.2     v0\.6\.2   No
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-af\fR
.
.IP "" 4
.
.nf

Update all installed packages\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package       Installed  Latest   Needs update
  treesize      v0\.2\.0     v0\.2\.1   Yes
  clippy        v0\.0\.1     v0\.0\.99  Yes
  clippy_lints  v0\.0\.1     v0\.0\.99  Yes
  racer         v1\.2\.10    v1\.2\.10  No

  Updating racer
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading racer v1\.2\.10
     [\.\.\.]
     Compiling racer v1\.2\.10
      Finished release [optimized] target(s) in 51\.43 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\eracer\.exe

  Updating clippy
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading clippy v0\.0\.99
     [\.\.\.]
     Compiling clippy v0\.0\.99
     [\.\.\.]
  error: failed to compile `clippy v0\.0\.99`, intermediate artifacts can be found at `T:\e\-_\-TEM~1\ecargo\-install\.WOcMlrKQ5Sok`

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updating clippy_lints
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
  error: specified package has no binaries

  Updated 2 packages\.
  Failed to update clippy, clippy_lints\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-i checksums rustfmt treesize\fR
.
.IP "" 4
.
.nf

Install specified packages, their installation status notwithstanding

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package    Installed  Latest   Needs update
  checksums             v0\.5\.2   Yes
  treesize   v0\.2\.0     v0\.2\.1   Yes
  rustfmt    v0\.6\.2     v0\.6\.2   No

  Installing checksums
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading checksums v0\.5\.2
     [\.\.\.]
     Compiling checksums v0\.5\.2
      Finished release [optimized] target(s) in 95\.2 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\echecksums\.exe

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updated 2 packages\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-ag\fR
.
.IP "" 4
.
.nf

Update all installed packages, including ones from git\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package         Installed  Latest   Needs update
  checksums       v0\.5\.0     v0\.5\.2   Yes
  cargo\-count     v0\.2\.2     v0\.2\.2   No

  Updating checksums
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading checksums v0\.5\.2
     [\.\.\.]
     Compiling checksums v0\.5\.2
      Finished release [optimized] target(s) in 95\.2 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\echecksums\.exe

  Updated 1 package\.

  Package                Installed  Latest   Needs update
  alacritty              eb231b3    5f78857  Yes
  chattium\-oxide\-client  108a7b9    108a7b9  No

  Updating alacritty from https://github\.com/jwilm/alacritty
      Updating git repository `https://github\.com/jwilm/alacritty`
     Installing alacritty v0\.1\.0 (https://github\.com/jwilm/alacritty#5f788574)
     [\.\.\.]
     Compiling alacritty v0\.1\.0
      Finished release [optimized] target(s) in 127\.6 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\ealacritty\.exe

  Updated 1 package\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>, Yann Simon <\fIyann\.simon\.fr@gmail\.com\fR>, ven <\fIvendethiel@hotmail\.fr\fR>, Cat Plus Plus <\fIpiotrlegnica@piotrl\.pl\fR>, Liigo <\fIliigo@qq\.com\fR>, azyobuzin <\fIazyobuzin@users\.sourceforge\.jp\fR>, Tatsuyuki Ishi <\fIishitatsuyuki@gmail\.com\fR>, Tom Prince <\fItom\.prince@twistedmatrix\.com\fR>, Mateusz Mikuła <\fImati865@gmail\.com\fR>, sinkuu <\fIsinkuupump@gmail\.com\fR>, Alex Burka <\fIaburka@seas\.upenn\.edu\fR>, Matthias Krüger <\fImatthias\.krueger@famsik\.de\fR>, Daniel Holbert <\fIdholbert@cs\.stanford\.edu\fR>, Jonas Bushart <\fIjonas@bushart\.org\fR>, and Harrison Metzger <\fIharrisonmetz@gmail\.com\fR>
.
.SH "SPECIAL THANKS"
To all who support further development, in particular:
.
.IP "\(bu" 4
ThePhD
.
.IP "" 0
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update\fR>
