.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CARGO\-INSTALL\-UPDATE" "1" "November 2016" "cargo-update developers" ""
.
.SH "NAME"
\fBcargo\-install\-update\fR \- Cargo subcommand for checking and applying updates to installed executables
.
.SH "SYNOPSIS"
\fBcargo install\-update\fR [OPTIONS] [PACKAGE\.\.\.]
.
.SH "DESCRIPTION"
Cargo subcommand for checking and applying updates to installed executables\.
.
.P
This was mostly built out of a frustration with periodically checking for updates for my cargo\-installed executables, which was long and boring\.
.
.P
Only updates packages from the main repository\.
.
.P
Exit values and possible errors:
.
.IP "" 4
.
.nf

\-1 \- cargo subprocess was terminated by a signal (Linux\-only)
1  \- option parsing error
X  \- bubbled\-up cargo install exit value
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
\-a \-\-all
.
.IP "" 4
.
.nf

Update all currently installed executables\.

Exclusive with list of packages\. Required if list of packages not given\.
.
.fi
.
.IP "" 0
.
.P
[PACKAGE\.\.\.]
.
.IP "" 4
.
.nf

List of packages to update\.

Exclusive with \-\-all\. Required if \-\-all not given\.
.
.fi
.
.IP "" 0
.
.P
\-l \-\-list
.
.IP "" 4
.
.nf

Don\'t update any packages, just list them\.
.
.fi
.
.IP "" 0
.
.P
\-f \-\-force
.
.IP "" 4
.
.nf

Update all packages, regardless of whether they need to be version\-wise\.
.
.fi
.
.IP "" 0
.
.P
\-c \-\-cargo\-dir \fICARGO_DIR\fR
.
.IP "" 4
.
.nf

Set the directory containing cargo metadata\.

Required\. Default: "$CARGO_HOME", then $HOME/\.cargo", otherwise manual\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBcargo install\-update \-a\fR
.
.IP "" 4
.
.nf

Update all installed packages\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package         Installed  Latest   Needs update
  cargo\-count     v0\.2\.2     v0\.2\.2   No
  cargo\-graph     v0\.3\.0     v0\.3\.0   No
  cargo\-outdated  v0\.2\.0     v0\.2\.0   No
  checksums       v0\.5\.0     v0\.5\.2   Yes
  identicon       v0\.1\.1     v0\.1\.1   No
  racer           v1\.2\.10    v1\.2\.10  No
  rustfmt         v0\.6\.2     v0\.6\.2   No
  treesize        v0\.2\.0     v0\.2\.1   Yes

  Updating checksums
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading checksums v0\.5\.2
     [\.\.\.]
     Compiling checksums v0\.5\.2
      Finished release [optimized] target(s) in 95\.2 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\echecksums\.exe

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updated 2 packages\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update\fR \fIracer treesize cargo\-cln\fR
.
.IP "" 4
.
.nf

Only consider racer, treesize and cargo\-cln for updates\.
Since cargo\-cln is not installed, it\'ll be ignored\.

 Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package   Installed  Latest   Needs update
  racer     v1\.2\.10    v1\.2\.10  No
  treesize  v0\.2\.0     v0\.2\.1   Yes

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updated 1 package\.
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-al\fR
.
.IP "" 4
.
.nf

List all installed packages, don\'t update any\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package         Installed  Latest   Needs update
  cargo\-count     v0\.2\.2     v0\.2\.2   No
  cargo\-graph     v0\.3\.0     v0\.3\.0   No
  cargo\-outdated  v0\.2\.0     v0\.2\.0   No
  checksums       v0\.5\.0     v0\.5\.2   Yes
  identicon       v0\.1\.1     v0\.1\.1   No
  racer           v1\.2\.10    v1\.2\.10  No
  rustfmt         v0\.6\.2     v0\.6\.2   No
  treesize        v0\.2\.0     v0\.2\.1   Yes
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update \-af\fR
.
.IP "" 4
.
.nf

Update all installed packages\.

Example output:
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`

  Package       Installed  Latest   Needs update
  racer         v1\.2\.10    v1\.2\.10  No
  treesize      v0\.2\.0     v0\.2\.1   Yes
  clippy        v0\.0\.1     v0\.0\.99  Yes
  clippy_lints  v0\.0\.1     v0\.0\.99  Yes

  Updating racer
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading racer v1\.2\.10
     [\.\.\.]
     Compiling racer v1\.2\.10
      Finished release [optimized] target(s) in 51\.43 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\eracer\.exe

  Updating clippy
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading clippy v0\.0\.99
     [\.\.\.]
     Compiling clippy v0\.0\.99
     [\.\.\.]
  error: failed to compile `clippy v0\.0\.99`, intermediate artifacts can be found at `T:\e\-_\-TEM~1\ecargo\-install\.WOcMlrKQ5Sok`

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe

  Updating clippy_lints
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
  error: specified package has no binaries

  Updated 2 packages\.
  Failed to update clippy, clippy_lints\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>, Yann Simon <\fIyann\.simon\.fr@gmail\.com\fR>, ven <\fIvendethiel@hotmail\.fr\fR>, Cat Plus Plus <\fIpiotrlegnica@piotrl\.pl\fR>, and Liigo <\fIliigo@qq\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update\fR>
