.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CARGO\-INSTALL\-UPDATE" "1" "October 2016" "cargo-update developers" ""
.
.SH "NAME"
\fBcargo\-install\-update\fR \- Cargo subcommand for checking and applying updates to installed executables
.
.SH "SYNOPSIS"
\fBcargo install\-update\fR [\-\-all] [PACKAGE\.\.\.]
.
.SH "DESCRIPTION"
Cargo subcommand for checking and applying updates to installed executables\.
.
.P
This was mostly built out of a frustration with periodically checking for updates for my cargo\-installed executables, which was long and boring\.
.
.P
Only updates packages from the main repository\.
.
.P
Exit values and possible errors:
.
.IP "" 4
.
.nf

\-2 \- cargo install process was terminated by a signal (Linux\-only)
\-1 \- failed to acquire crates\.io auth token
1  \- option parsing error
X  \- bubbled\-up cargo install exit value
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
\-a \-\-all
.
.IP "" 4
.
.nf

Update all currently installed executables\.

Exclusive with list of packages\. Required if list of packages not given\.
.
.fi
.
.IP "" 0
.
.P
[PACKAGE\.\.\.]
.
.IP "" 4
.
.nf

List of packages to update\.

Exclusive with \-\-all\. Required if \-\-all not given\.
.
.fi
.
.IP "" 0
.
.P
\-c \-\-cargo\-dir \fICARGO_DIR\fR
.
.IP "" 4
.
.nf

Set the directory containing cargo metadata\.

Default: "$HOME/\.cargo"\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBcargo install\-update \-a\fR
.
.IP "" 4
.
.nf

Update all installed packages\.

Example output:
  Package         Installed  Latest   Needs update
  cargo\-count     v0\.2\.2     v0\.2\.2   No
  cargo\-graph     v0\.3\.0     v0\.3\.0   No
  cargo\-outdated  v0\.2\.0     v0\.2\.0   No
  checksums       v0\.5\.0     v0\.5\.2   Yes
  identicon       v0\.1\.1     v0\.1\.1   No
  racer           v1\.2\.10    v1\.2\.10  No
  rustfmt         v0\.6\.2     v0\.6\.2   No
  treesize        v0\.2\.0     v0\.2\.1   Yes

  Updating checksums
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading checksums v0\.5\.2
     [\.\.\.]
     Compiling checksums v0\.5\.2
      Finished release [optimized] target(s) in 95\.2 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\echecksums\.exe

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe
.
.fi
.
.IP "" 0
.
.P
\fBcargo install\-update\fR \fIracer treesize cargo\-cln\fR
.
.IP "" 4
.
.nf

Only consider racer, treesize and cargo\-cln for updates\.
Since cargo\-cln is not installed, it\'ll be ignored\.

 Example output:
  Package   Installed  Latest   Needs update
  racer     v1\.2\.10    v1\.2\.10  No
  treesize  v0\.2\.0     v0\.2\.1   Yes

  Updating treesize
      Updating registry `https://github\.com/rust\-lang/crates\.io\-index`
     Downloading treesize v0\.2\.1
     [\.\.\.]
     Compiling treesize v0\.2\.1
      Finished release [optimized] target(s) in 76\.77 secs
     Replacing D:\eUsers\enabijaczleweli\e\.cargo\ebin\etreesize\.exe
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/cargo\-update\fR>
